CREATE TABLE POSTAGEM
(
    ID_POSTAGEM    SERIAL      NOT NULL,
    TEXTO_POSTAGEM VARCHAR(250),
    TIT_POSTAGEM   VARCHAR(40) NOT NULL,
    ID_CRIADOR     SERIAL      NOT NULL,
    DATA_POSTAGEM  DATE        NOT NULL,
    ID_DISCIPLINA  SERIAL      NOT NULL
);
CREATE TABLE COMENTARIO
(
    ID_POSTAGEM      SERIAL NOT NULL,
    ID_COMENTARIO    SERIAL NOT NULL,
    ID_USUARIO       SERIAL NOT NULL,
    TEXTO_COMENTARIO VARCHAR(250),
    DATA_COMENTARIO  DATE   NOT NULL
);
CREATE TABLE VOTACAO_POSTAGEM
(
    ID_USUARIO  SERIAL     NOT NULL,
    ID_POSTAGEM SERIAL     NOT NULL,
    VOTO        NUMERIC(1) NOT NULL CHECK (VOTO BETWEEN 0 AND 5)
);
CREATE TABLE VOTACAO_COMENTARIO
(
    ID_USUARIO    SERIAL     NOT NULL,
    ID_COMENTARIO SERIAL     NOT NULL,
    VOTO          NUMERIC(1) NOT NULL CHECK (VOTO BETWEEN 0 AND 5)
);

CREATE TABLE ANEXO_POSTAGEM
(
    ID_POSTAGEM SERIAL       NOT NULL,
    ID_ANEXO    SERIAL       NOT NULL,
    NOME_ANEXO  VARCHAR(100) NOT NULL
);

-- Chaves primárias
ALTER TABLE POSTAGEM
    ADD CONSTRAINT POSTAGEM_PK PRIMARY KEY (ID_POSTAGEM);

ALTER TABLE COMENTARIO
    ADD CONSTRAINT COMENTARIO_PK PRIMARY KEY (ID_COMENTARIO);

ALTER TABLE VOTACAO_POSTAGEM
    ADD CONSTRAINT VOTACAO_POSTAGEM_PK PRIMARY KEY (ID_POSTAGEM, ID_USUARIO);

ALTER TABLE VOTACAO_COMENTARIO
    ADD CONSTRAINT VOTACAO_COMENTARIO_PK PRIMARY KEY (ID_COMENTARIO, ID_USUARIO);


-- Chaves estrangeiras
ALTER TABLE ANEXO_POSTAGEM
    ADD CONSTRAINT ANEXO_PK PRIMARY KEY (ID_POSTAGEM, ID_ANEXO);

ALTER TABLE COMENTARIO
    ADD CONSTRAINT COMENTARIO_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM)
        REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE;

ALTER TABLE VOTACAO_POSTAGEM
    ADD CONSTRAINT VOTACAO_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM)
        REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE;

ALTER TABLE VOTACAO_COMENTARIO
    ADD CONSTRAINT VOTACAO_COMENTARIO_FK FOREIGN KEY (ID_COMENTARIO)
        REFERENCES COMENTARIO (ID_COMENTARIO) ON DELETE CASCADE;


ALTER TABLE ANEXO_POSTAGEM
    ADD CONSTRAINT ANEXO_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM)
        REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE;

ALTER TABLE COMENTARIO
    ADD CONSTRAINT COMENTARIO_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID) ON DELETE CASCADE;

ALTER TABLE POSTAGEM
 ADD CONSTRAINT POSTAGEM_DISCIPLINA_FK FOREIGN KEY (ID_DISCIPLINA)
        REFERENCES DISCIPLINA (ID);

CREATE TABLE TAG_POSTAGEM (
  POSTAGEM	SERIAL	NOT NULL,
  TAG		SERIAL	NOT NULL,
  CONSTRAINT TAG_POSTAGEM_PK PRIMARY KEY (POSTAGEM, TAG),
  FOREIGN KEY (TAG) REFERENCES TAG (ID),
  FOREIGN KEY (POSTAGEM) REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE
);

CREATE TABLE POSTAGEM
(
    ID_POSTAGEM    SERIAL      NOT NULL,
    TEXTO_POSTAGEM VARCHAR(250),
    TIT_POSTAGEM   VARCHAR(40) NOT NULL,
    ID_CRIADOR     SERIAL      NOT NULL,
    DATA_POSTAGEM  DATE        NOT NULL,
    ID_DISCIPLINA  SERIAL      NOT NULL
);
CREATE TABLE COMENTARIO
(
    ID_POSTAGEM      SERIAL NOT NULL,
    ID_COMENTARIO    SERIAL NOT NULL,
    ID_USUARIO       SERIAL NOT NULL,
    TEXTO_COMENTARIO VARCHAR(250),
    DATA_COMENTARIO  DATE   NOT NULL
);
CREATE TABLE VOTACAO_POSTAGEM
(
    ID_USUARIO  SERIAL     NOT NULL,
    ID_POSTAGEM SERIAL     NOT NULL,
    VOTO        NUMERIC(1) NOT NULL CHECK (VOTO BETWEEN 0 AND 5)
);
CREATE TABLE VOTACAO_COMENTARIO
(
    ID_USUARIO    SERIAL     NOT NULL,
    ID_COMENTARIO SERIAL     NOT NULL,
    VOTO          NUMERIC(1) NOT NULL CHECK (VOTO BETWEEN 0 AND 5)
);

CREATE TABLE ANEXO_POSTAGEM
(
    ID_POSTAGEM SERIAL       NOT NULL,
    ID_ANEXO    SERIAL       NOT NULL,
    NOME_ANEXO  VARCHAR(100) NOT NULL
);

-- Chaves primárias
ALTER TABLE POSTAGEM
    ADD CONSTRAINT POSTAGEM_PK PRIMARY KEY (ID_POSTAGEM);

ALTER TABLE COMENTARIO
    ADD CONSTRAINT COMENTARIO_PK PRIMARY KEY (ID_COMENTARIO);

ALTER TABLE VOTACAO_POSTAGEM
    ADD CONSTRAINT VOTACAO_POSTAGEM_PK PRIMARY KEY (ID_POSTAGEM, ID_USUARIO);

ALTER TABLE VOTACAO_COMENTARIO
    ADD CONSTRAINT VOTACAO_COMENTARIO_PK PRIMARY KEY (ID_COMENTARIO, ID_USUARIO);


-- Chaves estrangeiras
ALTER TABLE ANEXO_POSTAGEM
    ADD CONSTRAINT ANEXO_PK PRIMARY KEY (ID_POSTAGEM, ID_ANEXO);

ALTER TABLE COMENTARIO
    ADD CONSTRAINT COMENTARIO_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM)
        REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE;

ALTER TABLE VOTACAO_POSTAGEM
    ADD CONSTRAINT VOTACAO_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM)
        REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE;

ALTER TABLE VOTACAO_COMENTARIO
    ADD CONSTRAINT VOTACAO_COMENTARIO_FK FOREIGN KEY (ID_COMENTARIO)
        REFERENCES COMENTARIO (ID_COMENTARIO) ON DELETE CASCADE;


ALTER TABLE ANEXO_POSTAGEM
    ADD CONSTRAINT ANEXO_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM)
        REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE;

ALTER TABLE COMENTARIO
    ADD CONSTRAINT COMENTARIO_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID) ON DELETE CASCADE;

ALTER TABLE POSTAGEM
 ADD CONSTRAINT POSTAGEM_DISCIPLINA_FK FOREIGN KEY (ID_DISCIPLINA)
        REFERENCES DISCIPLINA (ID);

CREATE TABLE TAG_POSTAGEM (
  POSTAGEM	SERIAL	NOT NULL,
  TAG		SERIAL	NOT NULL,
  CONSTRAINT TAG_POSTAGEM_PK PRIMARY KEY (POSTAGEM, TAG),
  FOREIGN KEY (TAG) REFERENCES TAG (ID),
  FOREIGN KEY (POSTAGEM) REFERENCES POSTAGEM (ID_POSTAGEM) ON DELETE CASCADE
);
