INSERT INTO CURSO (NOME) VALUES ('Ciência da Computação');
INSERT INTO CURSO (NOME) VALUES ('Sistema da Informação');
INSERT INTO CURSO (NOME) VALUES ('Direito');
INSERT INTO CURSO (NOME) VALUES ('Medicina');

INSERT INTO DISCIPLINA (NOME, PERIODO, ID_CURSO) VALUES ('Introdução a Programação',1,(SELECT ID FROM CURSO WHERE NOME = 'Ciência da Computação'));
INSERT INTO DISCIPLINA (NOME, PERIODO, ID_CURSO) VALUES ('Programação Orientada a Objetos',2,(SELECT ID FROM CURSO WHERE NOME = 'Ciência da Computação'));
INSERT INTO DISCIPLINA (NOME, PERIODO, ID_CURSO) VALUES ('Estrutura de Dados I',3,(SELECT ID FROM CURSO WHERE NOME = 'Ciência da Computação'));
INSERT INTO DISCIPLINA (NOME, PERIODO, ID_CURSO) VALUES ('Estrutura de Dados II',2,(SELECT ID FROM CURSO WHERE NOME = 'Ciência da Computação'));

INSERT INTO TAG (DESCRICAO) VALUES ('Programação');
INSERT INTO TAG (DESCRICAO) VALUES ('Banco de dados');
INSERT INTO TAG (DESCRICAO) VALUES ('Redes');


