CREATE EXTENSION UNACCENT;

CREATE TABLE curso (
    id   SERIAL                 NOT NULL,
    nome character varying(100) NOT NULL,
    CONSTRAINT curso_pkey PRIMARY KEY (id)
);

CREATE TABLE DISCIPLINA (
    ID  	   SERIAL       NOT NULL,
    NOME 	   VARCHAR(100) NOT NULL,
    PERIODO	   INT 		NOT NULL,
    ID_CURSO       SERIAL       NOT NULL,
    CONSTRAINT DISCIPLINA_PK PRIMARY KEY (ID),
    CONSTRAINT DISCIPLINA_CURSO_FK FOREIGN KEY (ID)
        REFERENCES CURSO (ID)
);


CREATE TABLE TAG (
  ID		SERIAL 	   	NOT NULL,
  DESCRICAO	VARCHAR(50)	NOT NULL,
  CONSTRAINT TAG_PK PRIMARY KEY (ID)
);
