CREATE TABLE TOPICODISCIPLINA
(
    ID_TOPICO     SERIAL NOT NULL,
    ID_DISCIPLINA SERIAL NOT NULL
);

CREATE TABLE TOPICO
(
    ID_TOPICO     SERIAL      NOT NULL,
    DSC_TOPICO    VARCHAR(50) NOT NULL,
    ID_DISCIPLINA SERIAL      NOT NULL
);

CREATE TABLE QUIZ
(
    ID_QUIZ   SERIAL      NOT NULL,
    DSC_QUIZ  VARCHAR(50) NOT NULL,
    ID_TOPICO SERIAL      NOT NULL
);

CREATE TABLE PERGUNTA
(
    ID_PERGUNTA  SERIAL       NOT NULL,
    ID_QUIZ      SERIAL       NOT NULL,
    DSC_PERGUNTA VARCHAR(200) NOT NULL,
    URL_IMAGEM   VARCHAR(200)
);

CREATE TABLE ESCOLHA
(
    ID_ESCOLHA  SERIAL       NOT NULL,
    ID_PERGUNTA SERIAL       NOT NULL,
    EXP_ESCOLHA VARCHAR(300) NOT NULL,
    DSC_ESCOLHA VARCHAR(100) NOT NULL,
    CORRETA     BOOL         NOT NULL
);

CREATE TABLE PONTUACAO
(
    ID_USUARIO      SERIAL     NOT NULL,
    ID_QUIZ         SERIAL     NOT NULL,
    VALOR_PONTUACAO NUMERIC(3) NOT NULL
);


-- Chaves primárias
ALTER TABLE TOPICO
    ADD CONSTRAINT TOPICO_PK PRIMARY KEY (ID_TOPICO);
ALTER TABLE QUIZ
    ADD CONSTRAINT QUIZ_PK PRIMARY KEY (ID_QUIZ);
ALTER TABLE PERGUNTA
    ADD CONSTRAINT PERGUNTA_PK PRIMARY KEY (ID_PERGUNTA);
ALTER TABLE ESCOLHA
    ADD CONSTRAINT ESCOLHA_PK PRIMARY KEY (ID_PERGUNTA, ID_ESCOLHA);
ALTER TABLE PONTUACAO
    ADD CONSTRAINT PONTUACAO_PK PRIMARY KEY (ID_USUARIO, ID_QUIZ);
ALTER TABLE TOPICODISCIPLINA
    ADD CONSTRAINT TOPICODISCIPLINA_PK PRIMARY KEY (ID_TOPICO, ID_DISCIPLINA);

-- Chaves estrangeiras
ALTER TABLE TOPICO
    ADD CONSTRAINT TOPICO_DISCIPLINA_FK FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID);
ALTER TABLE QUIZ
    ADD CONSTRAINT QUIZ_TOPICO_FK FOREIGN KEY (ID_TOPICO) REFERENCES TOPICO (ID_TOPICO) ON DELETE CASCADE;
ALTER TABLE PERGUNTA
    ADD CONSTRAINT PERGUNTA_QUIZ_FK FOREIGN KEY (ID_QUIZ) REFERENCES QUIZ (ID_QUIZ) ON DELETE CASCADE;
ALTER TABLE ESCOLHA
    ADD CONSTRAINT ESCOLHA_PERGUNTA_FK FOREIGN KEY (ID_PERGUNTA) REFERENCES PERGUNTA (ID_PERGUNTA) ON DELETE CASCADE;
ALTER TABLE PONTUACAO
    ADD CONSTRAINT PONTUACAO_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID);
ALTER TABLE PONTUACAO
    ADD CONSTRAINT PONTUACAO_QUIZ_FK FOREIGN KEY (ID_QUIZ) REFERENCES QUIZ (ID_QUIZ);
ALTER TABLE TOPICODISCIPLINA
    ADD CONSTRAINT TOPICODISCIPLINA_TOPICO_FK FOREIGN KEY (ID_TOPICO) REFERENCES TOPICO (ID_TOPICO);
ALTER TABLE TOPICODISCIPLINA
    ADD CONSTRAINT TOPICODISCIPLINA_DISCIPLINA_FK FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID);